site_name: MkDocs Test
site_url: htttp://www.testing.com


nav:
  - Home: index.md
  - Creating a New Project: new-project.md
  - Setting Themes: themes.md
  - Text Formatting: formatting.md
  - Admonitions: admonition.md

theme: readthedocs
markdown_extensions:
  - admonition
